spring:
  config:
    activate:
      on-profile: prod
  application:
    name: curd
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/crud?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
      username: crudUser
      password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6380
---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: crud
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://leevelop.com:2906/practice?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: org.mariadb.jdbc.Driver
      username:
      password: 
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6380