spring:
  config:
    activate:
      on-profile: local
  application:
    name: curd
  datasource:
    url: jdbc:mariadb://leevelop.com:2906/practice
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: crud
  datasource:
    hikari:
      url: jdbc:mariadb://leevelop.com:2906/practice
      driver-class-name: org.mariadb.jdbc.Driver
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: none